# Generated by Django 4.1 on 2022-08-11 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_update', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Menagers',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='web.basemodel')),
                ('verif_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'menagers',
            },
            bases=('web.basemodel',),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.basemodel')),
                ('name', models.CharField(max_length=25, null=True)),
                ('verif_code', models.CharField(max_length=50)),
                ('chat_id', models.CharField(max_length=50)),
                ('bank_details', models.CharField(max_length=250)),
                ('amount', models.IntegerField()),
                ('limit', models.IntegerField(null=True)),
                ('date_craete', models.DateTimeField()),
                ('status', models.CharField(max_length=20, null=True)),
                ('bill', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'db_table': 'orders',
            },
            bases=('web.basemodel',),
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='web.basemodel')),
                ('name', models.CharField(max_length=25, null=True)),
                ('verif_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chat_id', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users',
            },
            bases=('web.basemodel',),
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.basemodel')),
                ('amount_sum', models.IntegerField()),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.menagers')),
            ],
            options={
                'db_table': 'reports',
            },
            bases=('web.basemodel',),
        ),
    ]
