# Generated by Django 4.1 on 2022-08-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_projects_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='whatsapp',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='clients',
            name='lang',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
