# Generated by Django 4.1 on 2022-08-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_rename_whatsapp_clients_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('token', models.CharField(max_length=50)),
                ('bank_details', models.CharField(max_length=250)),
                ('amount', models.IntegerField()),
                ('limit', models.IntegerField()),
                ('date_craete', models.DateField(auto_now=True)),
                ('date_update', models.DateField(auto_now=True)),
                ('status', models.CharField(max_length=20)),
                ('bill', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
    ]
