# Generated by Django 4.1 on 2022-08-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='bill',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
