# Generated by Django 4.1 on 2022-08-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_orders_bill_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date_craete',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date_update',
            field=models.DateTimeField(),
        ),
    ]
